### ISSUE TITLE
Account got banned

### ISSUE THREAD

**Issue by aryadp** [inforkgodara/whatsapp-bulk-messages-without-saving-contacts#15]
whatsapp flagged the messages as spam and banned the account after just 3 messages sent, is there a way to prevent this? would adding a delay help?

**Comment by inforkgodara** [comment]
Hi, I am really sorry to hear. You cannot send messages to the people who have not saved your contact number. So put the request to WhatsApp to unban. They will unban you once they receive your request.

As I have already mentioned this repo for the educational purpose not to be meant for the commercial uses.

**Comment by inforkgodara** [comment]
If you want to use commercial purpose you should consider to take WhatsApp Business API access from the Meta Partners.
