### ISSUE TITLE
message is not sending 

### ISSUE THREAD

**Issue by karthiksibi5161** [inforkgodara/whatsapp-bulk-messages-without-saving-contacts#7]
i'm really impress your project now i need your help "Sorry message could not sent to 9995777882
Sorry message could not sent to 33999999999" actually this script execute like this but my number is real how to resolve this
sibibis5161@gmail.com my gmail frnd.

**Comment by srikard** [comment]
I think the button class name has changed.

**Comment by Lucky0108** [comment]
Did you found a solution for it?

**Comment by osBins** [comment]
As of 28th October 2022, using class name `_1Ae7k` instead of `_4sWnG` at https://github.com/inforkgodara/whatsapp-bulk-messages-without-saving-contacts/blob/10fd413b569c9b82b8d62d5182f7adecc96dd78a/script.py#L27  
solves the problem.

**Comment by miquelnebotaragon** [comment]
Hi! Good Morning!
I've the same problem, Whatsapp web it's open, but message is not sending... It's waiting since the error message appears. Can you help me? Thanks!
![OhZQ0JcWId](https://user-images.githubusercontent.com/57944755/210062712-89158bed-d2b6-4be1-bea4-0d426892eedd.png)

**Comment by MAFiA-6iXTY9iNE** [comment]
> e appears. Can you help me? Thanks!
_at 27th line_
`EC.element_to_be_clickable((By.CLASS_NAME, '_3XKXx')))`
**Change like this! Good to go..**

**Comment by rushi20139** [comment]
Message sent successfullu output recieved in terminal, but in reality the message is not sent !!

**Comment by inforkgodara** [comment]
Repo is updated in Sept 23 after change the class of Web WhatsApp.
