### ISSUE TITLE
Message sent successfully but not in actual whatsapp. 

### ISSUE THREAD

**Issue by rushi20139** [inforkgodara/whatsapp-bulk-messages-without-saving-contacts#9]
The terminal is showing message sent successfully to the number but actually it is not sent.

**Comment by rakhaevandy27** [comment]
its cause by the class element on the whatsapp web that has been updated
please see on https://github.com/inforkgodara/whatsapp-bulk-messages-without-saving-contacts/blob/e57409faec0e9900661640e9b85a813fad16a82b/script.py#L27 and update it to `_3XKXx`

**Comment by inforkgodara** [comment]
Repository has been updated with the new class name.
